server:
  port: 6004
  context-path: /user
management:
  context-path: /admin
  port: 6005
api.version: v1
spring:
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://${observatory.ip}:${observatory.port}/eureka/
  instance:
    prefer-ip-address: true
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health

observatory:
  ip: 192.168.40.155
  port: 8761