server:
  port: 6000
  context-path: /order
management:
  context-path: /admin
  port: 6001

api.version: v1
spring:
  jpa:
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: 61.105.58.243
    username: order
    password: bnp@1234
    virtual-host: monitor

user:
  context-path: /user
  version: v1
product:
  context-path: /product
  version: v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://${observatory.ip}:${observatory.port}/eureka/
  instance:
    prefer-ip-address: true
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health

observatory:
  ip: 192.168.40.155
  port: 8761
feign:
  hystrix:
    enabled: true
  oauth2:
    enabled: true

uaa:
  client:
    id: order
    client-id: order
    client-secret: shoppingmall
    access-token-uri: http://localhost:8010/uaa/oauth/token
    user-authorization-uri: http://localhost:8010/uaa/oauth/authorize
    scope: trust-client
